name:                stm32f-ivory-blinky
version:             0.1.0.0
github:              "WhoMeNope/stm32f-ivory-blinky"
license:             BSD3
author:              "Martin Toman"
maintainer:          "toman.martin@live.com"
copyright:           "Martin Toman"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/WhoMeNope/stm32f-ivory-blinky#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  stm32f-ivory-blinky-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ivory
    - ivory-hw
    - ivory-stdlib
    - ivory-backend-c
    - ivory-bsp-stm32
    - tower >= 0.9
    - tower-config
    - tower-freertos-stm32
    - stm32f-ivory-blinky
